### ISSUE TITLE
Correção no getFieldDecorator do forms de registro - Nome undefined no dashboard da EJ

### ISSUE THREAD

**Issue by JohnnyBaptista** [EJComp-Unesp/Dvora-Frontend#66]
Atualmente no FormItem do forms de registro está com o  fieldDecorator do input está com o valor errado, causando um erro no cadastro da EJ e deixando o nome como undefined.

```javascript
<Form.Item>
    {getFieldDecorator("nome", {
       rules: [{ required: true, message: "Please input your username!" }],
     })(
          <Input
             size="large"
             prefix={<Icon type="user" style={{ color: "rgba(0,0,0,.25)" }} />}
             placeholder="Nome da Empresa Júnior"
          />
     )}
<Form.Item>
```

Está é a forma atual, basta mudar o `fieldDecorator` para `name` ao invés de `nome`.
Após isso testar a criação da EJ e verificar se o nome aparece no dashboard corretamente

**Comment by karenalmeida18** [comment]
Encontrei a branch que já haviamos feito as correções e atualizei ela no pr #68
