### ISSUE TITLE
Desabilitar tela de perfil

### ISSUE THREAD

**Issue by JohnnyBaptista** [EJComp-Unesp/Dvora-Frontend#78]
Para esse primeiro release, não será utilizado a página de login, por isso deve ser desativada.
Para alcançar isto, basta retirar o redirecionamento para a rota de login ao clicar na ícone de perfil

**Comment by etakao** [comment]
Como desabilitaremos a tela de perfil, posso tirar aquele redirecionamento que tinha pra EJ? (redirecionava pra tela de equipe)

**Comment by JohnnyBaptista** [comment]
> Como desabilitaremos a tela de perfil, posso tirar aquele redirecionamento que tinha pra EJ? (redirecionava pra tela de equipe)

Siim, isso mesmo.
