### ISSUE TITLE
Bug ao rolar na hora de selecionar diretoria

### ISSUE THREAD

**Issue by viniciusveu** [EJComp-Unesp/Dvora-Frontend#79]
![Captura de tela de 2020-08-11 19-23-22](https://user-images.githubusercontent.com/32825138/89960826-692a6a00-dc16-11ea-847a-bf5aa1804897.png)

**Comment by viniciusveu** [comment]
Obs.: Verificar se isso aconteceu só no meu navegador e depois verificar se em editar EJ esta com o mesmo problema.

**Comment by JohnnyBaptista** [comment]
Não tem descrição do erro. O que ocorre? @viniciusveu

**Comment by viniciusveu** [comment]
Se clicar para inserir a diretoria aparece a caixa com as possíveis seleções de direotiras cadastradas, porém se antes de clicar na opção desejada rolarmos a página, essas opções ficam desgrudadas do campo de diretoria (como na imagem).
