### ISSUE TITLE
Bug ao atualizar dados de membro

### ISSUE THREAD

**Issue by viniciusveu** [EJComp-Unesp/Dvora-Frontend#80]
Se for atualizar dados de um membro está sendo necessário inserir até as informações que o usuário não quer atualizar.
![Captura de tela de 2020-08-11 19-24-11](https://user-images.githubusercontent.com/32825138/89960976-d76f2c80-dc16-11ea-92b4-b027b8801a10.png)

**Comment by JohnnyBaptista** [comment]
Para resolver isso, basta iniciar os campos do formulário com os valores já definidos. Aí ele apenas mudará o que desejar.
Continue deixando os campos como required para não evitar ficar em branco
