### ISSUE TITLE
Itens do menu dropdown da navbar 

### ISSUE THREAD

**Issue by LeoYudi** [EJComp-Unesp/Dvora-Frontend#89]
![image](https://user-images.githubusercontent.com/38156839/90341350-46f96900-dfd5-11ea-9bec-0d4c85ad725f.png)

Como mostrado no print, existem itens que não são utilizados.

**Comment by JohnnyBaptista** [comment]
Fechando por estar corrigido no PR #88
Foi substituído por "em desenvolvimento"
